### ISSUE TITLE
Failed to connect to peripheral

### ISSUE THREAD

**Issue by FelixNiedermann** [drndos/mikettle#14]
I'm Executin the following:

`pi@pi:~/kettle $ python3 demo.py connect B8:7C:6F:A9:08:61 1116

DEBUG:mikettle.mikettle:Init Mikettle with mac B8:7C:6F:A9:08:61 and pid 1116
Authenticating
Getting data from mi Kettle
FW: 7.5.10
Traceback (most recent call last):
  File "/home/pi/kettle/demo.py", line 77, in <module>
    main()
  File "/home/pi/kettle/demo.py", line 73, in main
    args.func(args)
  File "/home/pi/kettle/demo.py", line 47, in connect
    print("Name: {}".format(kettle.name()))
  File "/home/pi/kettle/mikettle/mikettle.py", line 87, in name
    self.connect()
  File "/home/pi/kettle/mikettle/mikettle.py", line 82, in connect
    self._p = Peripheral(deviceAddr=self._mac, iface=self._iface)
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral B8:7C:6F:A9:08:61, addr type: public`

The kettle gives a peep sound (With other product id it does not, so I think that part is right) but it's not able to fully connect to the Mi Kettle. Any ideas?

**Comment by Worrah** [comment]
same for me

**Comment by Miliks** [comment]
Any update, i'm facing the same issue

**Comment by danfe** [comment]
> The kettle gives a peep sound (with other product ID it does not, so I think that part is right) but it's not able to fully connect to the Mi Kettle. Any ideas?

> Any update, I'm facing the same issue

This was actually debugged in the at-first-glance-unrelated issue #4.  I had the same problem with two nearly identical YM-K1501 kettles, one released in 2018.04 and another in 2019.04, both being `yunmi.kettle.v1`.  Suggested solution (#5) had fixed it for me.  Unfortunately, this pull request (and some useful others) had never been merged.
